### ISSUE TITLE
Question on using pharmaRTF in reporting

### ISSUE THREAD

**Issue by ghost** [atorus-research/pharmaRTF#3]
Is it possible to use this package to generate a word report which has proper table formatting as shown in this package but also with proper table numbering and referencing?

**Comment by elimillera** [comment]
Hello Zhenglei,

Thanks for the question! Right now pharmaRTF is focused on producing single tables for inclusion in a report instead of report creation workflow. We understand that every organization has different nuance to the way they try to combine reports. Given the way that things work with our outputs (i.e. dynamic page numbering), pharmaRTF would work best in a process where the RTF is converted into another format like PDF and then combined. 

Let me know if you have any other questions,
Eli
